#ifndef F15_SE2_EGAME
#define F15_SE2_EGAME
#include "inttype.h"
#include "struct.h"
#include "comm.h"
#include "pointers.h"

#include <stdio.h>

#if !defined(MSDOS)
#define far
#ifndef pascal
#define pascal
#endif
#endif

#define __int32 long
#define __int8 char
#define __cdecl
#define __far far
/*
 * The 3D world data lives in one contiguous far buffer. The aircraft-model region
 * (g_aircraftModels) sits AIRCRAFT_MODELS_OFFSET bytes into the region/object buffer
 * (g_world3dData): shapeDataOffset() (egmath.c) addresses models as the offset
 * difference &g_aircraftModels[off] - g_world3dData and drawWorldObject() re-adds it, so the
 * round-trip only resolves at that exact spacing.
 *
 * Reference build (asm): g_world3dData and g_aircraftModels are two distinct symbols pinned
 * at the right offsets by egfarbu2.asm, matching the original's codegen (which loads
 * the model segment dynamically because the two symbols are independent).
 *
 * Asm-free builds (NO_ASM / 64-bit): g_world3dData is a single contiguous buffer
 * (egfarbuf.c) and g_aircraftModels is a view into it at the fixed offset. The spacing is
 * then guaranteed by construction and is correct under both the 16-bit far model and
 * the flat 64-bit layout, with no dependence on linker placement.
 */
#define AIRCRAFT_MODELS_OFFSET 0xADD4
#ifdef BUGFIX
extern char far g_world3dData[];
#else
extern unsigned char far g_world3dData[];
#endif
#ifdef NO_ASM
#define g_aircraftModels (g_world3dData + AIRCRAFT_MODELS_OFFSET)
#else
extern char far g_aircraftModels[];
#endif
#define DOS_SET_IRQH 0x25
#define PORT_PIT_TIME0 0x40
#define PORT_PIT_CNTRL 0x43
#define COMM_GFXOVL_SEG 0x1a
#define COMM_SNDOVL_SEG 0x1c
#define COMM_MISCOVL_SEG 0x1e
#define COMM_GFXBUF_PTR 0x20
#define COMM_HERC_FLAG 0x24
#define COMM_SETUP_DONE_OFFSET 0x26
#define COMM_SETUP_GFXMODE_OFFSET 0x30
#define COMM_UNK7 0x38  /* weaponType */
#define COMM_JOYDATA_OFF 0x48
#define COMM_USEJOY_OFF 0x72
#define COMM_GFXMODE_OFFSET 0x78
#define COMM_WORLDBUF 0x7a
#define OFF_IACA_START 0x4f0
#define COMM_GAMEDATA_OFFSET 0x120e
#define IRQ_CBREAK 0x1b
#define GAMEDATA_THEATER 0x38
#define GAMEDATA_DIFFICULTY 0x3e
#define GAMEDATA_UNK4 0x40
#define WAYPT_PRIMARY 0x1
#define WAYPT_SECONDARY 0x2
#define WAYPT_BASE 0x3
#define IRQ_VIDEO 0x10
#define OVL_HDR_CODESEG 0x18
#define OVL_HDR_FIRSTIDX 0x1c
#define OVL_HDR_SLOTCOUNT 0x22
#define OVL_HDR_FIRSTPTR 0x24
void __cdecl drawCockpit();
void runGameSession();
void doNothing3();
void doNothing4();
void __cdecl gfxInit();
// bytes outside routine, potential module boundary at 0x2e1
int loadF15DgtlBin();
void drawProjectionSphere(int arg_0);
void setupOverlaySlots(uint16 addr);
void updateFrame(void);
void dispatchKeyScancode();
void countermeasures(int kind);
void tickMessageTimers();
void updateBulletsAndFire();
void updateTracerParticles();
void applyGravityFall();
void initFrameRandom();
void resetSimObjectLocks();
void initWeaponLoadout(void);
void drawWeaponAmmo();
void drawWeaponSelectMarker(int weaponIdx);
void finalizeMission(int outcome);
void scheduleEventCheck(int eventObjIdx, unsigned int priority);
void scheduleTimedEvent(int keyVal, int delay);
void generateRandomRadioMessage();
void appendMapEvent(int eventType, int arg_2);
void placeString(int waypointIdx);
void initMissionStrings();
void findWaypointFeatures();
void moveDataFar();
void moveStuff();
void moveNearFar(void *nearPtr, int count);
int setCommWorldbufPtr();
void callLoad3DAll();
void loadRegion3D();
void render3DView(int, int, int, long, long, long, int, int, int, int);
void waitFrameSync(int frames);
void loadColorPalette(int idx);
// (prototype local to callers — eg3dview.c)
uint32 scaleCoordToLod(int level, uint32 coord);
int process3dg(int lod, int col, int row);
void load3DAll();
void __cdecl load3D3(char *);
void __cdecl load3DT(char *);
void load3DG();
void __cdecl printError(const char *);
void __cdecl strcpyFromDot(char *dst, char *src);
struct TileObject* findNearestTileObject(uint32 worldX, uint32 worldY);
void addTileEntry(char *a, int b, char c);
int lookupTileEntry(int lod, int subIndex, int tileX, int tileY);
void drawNearestTileObject(uint32 coord1, uint32 coord2, uint32 coord3);
void renderMapTerrain(char *, int, int, int);
void drawMapTiles(int originX, int originY, int zoomShift);
void computeTileBounds(int *, int *, int *, int *);
void worldToTileIndex(int, int, int *, int *);
void drawMapTileObject(char far *, int, int);
void drawModelPoint(int, int);
void buildVertexSignMask(int, int);
void projectModelVertices(int screenX, int screenY);
int aspectScaleY(int screenY);
void setup3DTransform(char*, int, int, int, int, int, int, int);
void rasterize3DWorld();
void setupViewport(char *rect);
void setViewRotation(int, int, int);
void setViewPosition(int posX, int posY, int posZ);
void setupDac();
int fixedMulQ14(int arg_0, int arg_2);
int cosine(int);
int sine(int arg_0);
void installCBreakHandler();
void restoreCBreakHandler();
void runGameLoop();
void gameMainLoop();
void setTimerIrqHandler();
void restoreTimerIrqHandler();
int getTimeOfDay();
void advanceFrameTick();
void stepFlightModel();
void applyRotationDelta(int param_1, int param_2);
void computeAttitudeAngles(void);
void rebuildOrientation();
unsigned signedRatio16(int, int);
int valueToAngle(int value);
int complementAngle(int arg_0);
int isqrt(int value);
void renderFrame();
void UpdateThrottleState(void);
void drawFuelGauge(void);
void drawVectorShape(int16 *shapeData);
void waitForKeyPress(void);
void updateThreatSites();
void fireGroundThreat(int param_1);
int computeThreatRangeBearing(int threatX, int threatY, int arg_4, int threatType, int *outBearing, int *arg_a);
void updateThreatAlert();
int computeThreatScore();
void updateObjects(void);
void fireAirThreat(int param_1);
void spawnEnemyAircraft(int slot, int objType);
void updateThreatTargeting();
int samCanAcquireTarget(int slot, int targetX, int targetY, int param_4, int mode);
void destroyAircraft(int objIdx);
void destroyGroundTarget(int param_1);
int markTargetReached(int targetIdx);
void bombTarget(void);
void fireMissile();
void testWorldPosVisible(int worldX, int worldY, int worldZ);
void clearStatusPanel();
void renderHudFrame();
void __cdecl setActivePanel(int);
void refreshActivePanel(int panelId);
void initTacMapView(void);
void redrawTacMap(int, int);
void zoomIn(void);
void zoomOut(void);
int mapXToScreen();
int mapYToScreen();
int plotMapObject(int mapX, int mapY, int color, int big);
int objectToScreen(int mapX, int mapY, int16 *outScreenX, int16 *outScreenY);
int readMapPixelColor(int mapX, int mapY);
void __cdecl drawMapRangeArc(int, int, int, int, int, int, int);
void drawMapLine(int x1, int y1, int x2, int y2);
void drawFullscreenLine(int x1, int y1, int x2, int y2);
void drawViewportLine(int x1, int y1, int x2, int y2);
void drawClippedLineRegion(int x1, int y1, int x2, int y2, int clipLeft, int arg_a, int arg_c, int arg_e, int drawBothPages);
void drawScreenLineOnePage(int x1, int y1, int x2, int y2);
void __cdecl drawHudViewLine(int, int, int, int);
void __cdecl setDrawColor(int);
void fillRectBoth(int x1, int y1, int x2, int y2);
void drawColorPoint();
void drawMapPoint(int, int, int);
void switchIndicatorColor(int indicatorIdx, int color);
void __cdecl drawPanelText(int, char*, int);
void __cdecl fillPanelBox(int, int);
int __cdecl drawCenteredLabelBox(int, char *);
void __cdecl drawStringBothPages(const char *, int, int, int);
void drawStringActivePage(const char*, int, int, int);
void __cdecl drawStringCentered(int16 *, const char *, int, int, int);
void drawNumber(int, int, int, int);
int readScreenPixel(int screenX, int screenY);
void tempStrcpy(char *src);
void setTimedMessage(char *message);
int missileTargetCompat(int param_1, int objIdx);
void drawTacticalMap(char page);
void drawMapMarkerBox(int arg_0, int arg_2, int color);
void projectMapPoint(int mapX, int mapY);
void blitGaugeSprite(int srcCol, int srcRow, int destX, int destY);
extern struct SpriteParams gaugeSpriteParams;
void blitSprite(int destX, int destY, int srcX, int srcY, int spriteWidth, int arg_a, int arg_c);
extern struct SpriteParams blitSpriteParams;
extern struct BulletTrack bulletTracks[20];
void cacheScopePanel();
void restoreScopePanel();
void captureScopePanel();
void updateTargetLock();
void drawHudWorldOverlay(void);
void drawTargetBox(int, int, int, int);
void drawMissileLock(void);
void __cdecl drawTargetLabel(char *, int, int);
void buildRangeString(int rangeRaw);
void projectWorldToHud(int worldX, int worldY, int worldZ);
long rotateVectorComponent(int axis, int vecX, int vecY, int vecZ);
int findWaypointEntry(int mapX, int mapY);
int computeMapTargetRange(int targetIdx);
int computeSimObjectRange(int objIdx);
int computeTargetBearing(int targetX, int targetY, int wantBearing);
int computeLoftAngle();
int getTargetSymbol(int wpIdx);
int isTargetOverWater(int wpIdx);
void load15Flt3d3();
void drawWorldObject(int shapeId, long worldX, long worldY, int altitude, int param_5, int param_6, int param_7, int scaleShift);
void drawTargetView(int shapeId, int worldX, int worldY, int altitude, int param_5, int param_6, int param_7, int mode, int shift);
int shapeDataOffset(int param_1);
int clampRange(int value, int minVal, int maxVal);
int clampValue(int value, int min, int max);
int rangeApprox(int dx, int dy);
int computeBearing(int arg_0, int arg_1);
int sinMul(int angle, int value);
int cosMul(int angle, int value);
int signOf(int value);
void seedRng(void);
int randomRange(int);
int readAxisInput(int param_1);
int keyDispatch(uint16 scanCode);
void selectMissile();
void makeSound(int soundId, int priority);
void playVoiceCue(int weaponIdx);
void updateEngineSound(void);
void recalcTimeScale(void);
void setupLodDistances(void);
void exitSlowMotion();
void disableTextBlink(void);
int __cdecl openFileWrapper(const char *, int);
int createFileWrapper(const char* filename, int attr);
void closeFileWrapper(int handle);
int readFile1Wrapper();
int readFile2Wrapper();
int writeFileAtRawWrapper();
int __cdecl openFile(const char *, int);
int createFile(const char *arg_0, int arg_1);
void closeFile(int arg_0);
int readFile1(int arg_0, int arg_1, int arg_2);
int readFile2(int arg_0, int arg_1, int arg_2, int arg_3);
int writeFileAtRaw(int arg_0, int arg_1, int arg_2, int arg_3, int arg_4);
 // 2 parameters correct
void openBlitClosePic(char* path, int arg_2);
 // 2 parameters correct
void picBlit(int handle, int unk);
void pascal shiftLongLeftInPlace(int count, long *ptr);
void pascal shiftLongRightInPlace(int count, long *ptr);
int far drawPolygonOutline(int, int, int*, int);
void installDivZeroHandler();
void installDivZeroVector();
int far drawFlatHorizon(int);
void renderHorizonSky();
#ifdef NO_ASM
void far projectSceneObject(char *, int, int, int, int, int, int);
#else
void far projectSceneObject();
#endif
void storeObjTransformByOpcode();
int far transformAndCullObjectFar(int, int, int);
int far advanceModelPointerLod();
int far renderSortedListFar();
int far rotatePoint3dFar();
void rotatePoint3d();
int far transformModelVerticesFar();
int far projectModelEdgesFar();
int far buildRotationMatrixFar(int16* param_1, int param_2, int param_3, int param_4);
int far multiplyMatrix3x3Far(int param_1, int param_2, int16* param_3);
int far drawModelDisplayList();
int far fillSpanRect(int16* param_1, int param_2, int param_3, int param_4, int param_5);
int far drawClipLineGlobal();
int far flushSpanDirtyRect();
int far resetScanlineSpans();
int far clipAndRasterizeEdge();
// bytes outside routine, potential module boundary at 0x9
void __cdecl __far setupInstrumentLayoutFar();
int far initJoystickCalibration();
void seedJoystickBaseline();
int far readCalibratedJoystick();
void readJoystickHardware();
void computeJoystickAxis();
int far restoreJoystickData(uint8 FAR *ptr);
void far copyJoystickData(uint8 FAR *ptr);
int far setInt9Handler();
int far restoreInt9Handler();
int int9Handler();
// bytes outside routine, potential module boundary at 0x189
extern uint8 aLb_xxx[];
extern uint8 aPg_xxx[];
extern uint8 aVn_xxx[];
extern uint8 aMe_xxx[];
extern uint8 aNc_xxx[];
extern uint8 aCe_xxx[];
extern uint8 aJp_xxx[];
extern uint8 aNa_xxx[];
extern uint8 g_dacSupported;
extern uint8 exitCode;
extern int16 gfxModeUnset;
extern int16 f15DgtlResult;
extern char *regnStr;
extern char *scenarioPlh[];
extern char a256pit_pic[];
extern char aCockpit_pic[];
extern uint8 aF15dgtl_bin[];
extern int16 f15dgtlAddr;
extern int allocSize;
extern int16 g_sphereColor;
extern int16 g_viewCenterX;
extern int16 g_viewCenterY;
extern int16 g_sphereRingTable[16];
extern uint8 ovlInsaneFlag;
extern uint8 aErrorReleasingOverlay[];
extern char aSafeLanding[];
extern char aReadyForTakeof[];
extern char aWeaponsRepleni[];
extern char aAutomaticLandi[];
extern struct Waypoint waypoints[];
extern int16 waypointIndex;
extern int16 g_unusedWaypointTail;
extern struct Weapon aNone[];
extern uint8 aSa2[];
extern uint8 aSa5[];
extern uint8 aSa8b[];
extern uint8 aSa10[];
extern uint8 aSa11[];
extern uint8 aSa12[];
extern uint8 aSa13[];
extern uint8 aSaN4[];
extern uint8 aSaN5[];
extern uint8 aSaN6[];
extern uint8 aSaN7[];
extern uint8 aHawk[];
extern uint8 aRapier[];
extern uint8 aTiger[];
extern uint8 aSeacat[];
extern uint8 aIl76[];
extern struct AircraftType aircraftTypes[]; /* 32-byte type records */
extern uint8 aMig25[];
extern uint8 aFoxbat[];
extern uint8 aMig29[];
extern uint8 aFulcrum[];
extern uint8 aF1[];
extern uint8 aMirage[];
extern uint8 aSu27[];
extern uint8 aFlanker[];
extern uint8 aIl76_0[];
extern uint8 aMainstay[];
extern uint8 aF4e[];
extern uint8 aAn72[];
extern struct Sam sams[39];
extern int16 g_bombDamageMask;
extern int16 g_fuelRemaining;
extern int16 g_eventTimers[];
extern struct MissileSpec missleSpec[];
extern int16 missileSpecIndex;
extern int16 g_gunAmmo;
extern int16 g_autopilotAltitude;
extern int16 g_missionStatus;
extern int16 g_difficultyTier;
extern int16 g_nightMode;
extern int16 g_inputDisabled;
extern int16 g_hudVisible;
extern int16 g_frameRateScaling;
extern struct Missile missiles[20];
extern struct MapEvent mapEvents[]; /* 12-byte marker records */
extern struct Particle g_particles[8];
extern int16 g_smokeParticleSlot;
extern int16 g_maneuverTable[3][8][8];
extern struct Projectile g_projectiles[];
extern int16 g_threatScopeRange;
extern int16 g_trackedEnemyIdx;
/* Free-running per-frame counter (DGROUP 0x336E8). Incremented once per
 * gameMainLoop iteration in updateFrame(). NOT the RNG seed (that's the C
 * lib rand()/srand via seedRng) and NOT a wall-clock/ms counter (real time
 * is tracked by g_frameTimingAccum + the BIOS timer, which recalibrate the rate
 * g_frameRateScaling). initFrameRandom() seeds it with a RANDOM phase
 * (randomRange(0x1000) & 0x7ff8), so its absolute value is meaningless --
 * only deltas, deadlines (g_directorEventDeadline = delay*g_frameRateScaling + frameTick) and low
 * bits (& 7/& 0xf, % g_frameRateScaling) matter, e.g. animation/AI phase staggering. */
extern int16 frameTick;
extern int16 g_autopilotEngaged;
extern int16 g_gearDownArmed;
extern int16 g_destroyedCueDeadline;
extern int16 g_threatActiveTimer;
extern int16 g_airTargetLock;
extern int16 g_groundTargetLock;
extern int16 g_smokeSourceIdx;
extern int16 g_scopeSweepTimer;
extern int16 g_threatToneLevel;
extern int16 g_padlockAircraft;
extern int16 g_externalCamDist;
extern int16 g_prevThreatIndex;
extern int16 g_inLandingCorridor;
extern int16 g_render3DTiles;
extern int16 g_landingDoneFlag;
extern uint16 g_frameRateAccum;
extern int16 g_slowMotionMode;
extern int16 g_directorEventDeadline;
extern int g_directorMode;
extern int16 g_resupplyCount;
extern int16 g_autoLandingActive;
extern int16 g_landingTimer;
extern uint8 aStoresExhauste[];
extern uint8 aFlare[];
extern uint8 aChaff[];
extern uint8 aReleased[];
extern uint8 strColon[];
extern char aGun[];
extern int16 g_weaponMarkerBoxX[];
extern uint8 aS[];
extern int16 g_weaponMarkerSel;
extern char aOnPatrol[];
extern char aF15StrikeEagle[];
extern char aAt[];
extern uint8 jmp_0[];
extern uint8 jmp_1[];
extern uint8 jmp_2[];
extern uint8 jmp_3[];
extern uint8 jmp_4[];
extern uint8 jmp_5[];
extern uint8 jmp_6[];
extern uint8 jmp_7[];
extern uint8 jmp_8[];
extern uint8 jmp_9[];
extern uint8 jmp_10[];
extern uint8 jmp_11[];
extern uint8 jmp_12[];
extern uint8 jmp_13[];
extern uint8 jmp_14[];
extern uint8 jmp_15[];
extern uint8 jmp_16[];
extern uint8 jmp_17[];
extern uint8 jmp_18[];
extern uint8 jmp_19[];
extern uint8 jmp_20[];
extern uint8 jmp_21[];
extern uint8 jmp_22[];
extern uint8 jmp_23[];
extern uint8 jmp_24[];
extern uint8 jmp_25[];
extern uint8 jmp_26[];
extern uint8 jmp_27[];
extern uint8 jmp_28[];
extern uint8 jmp_29[];
extern uint8 jmp_30[];
extern uint8 jmp_31[];
extern uint8 jmp_32[];
extern uint8 jmp_33[];
extern uint8 jmp_34[];
extern uint8 jmp_35[];
extern uint8 jmp_36[];
extern uint8 jmp_37[];
extern uint8 jmp_38[];
extern uint8 jmp_39[];
extern uint8 jmp_40[];
extern uint8 jmp_41[];
extern uint8 jmp_42[];
extern uint8 jmp_43[];
extern uint8 jmp_44[];
extern uint8 jmp_45[];
extern uint8 jmp_46[];
extern uint8 jmp_47[];
extern uint8 jmp_48[];
extern uint8 jmp_49[];
extern uint8 jmp_50[];
extern uint8 jmp_51[];
extern uint8 jmp_52[];
extern uint8 jmp_53[];
extern uint8 jmp_54[];
extern uint8 jmp_55[];
extern uint8 jmp_56[];
extern uint8 jmp_57[];
extern uint8 jmp_58[];
extern uint8 jmp_59[];
extern uint8 jmp_60[];
extern uint8 jmp_61[];
extern uint8 jmp_62[];
extern uint8 jmp_63[];
extern uint8 jmp_64[];
extern uint8 jmp_65[];
extern uint8 g_renderPageToggle;
extern uint8 g_colorPalettes[];
extern int16 g_dirGridOffsets[];
extern struct NeighborSampling g_neighborSampling;
extern int16 g_lodObjectCount[];
extern int16 g_lodGridDim[];
extern size_t size3d3;
extern unsigned int buf3d3[];
extern unsigned int size3d3_2;
extern int16 sign3dt;
extern unsigned int sizes3dt[];
extern unsigned int matrix3dt[5][32];
extern int16 g_modelOffsetTable[];
extern size_t size3d3_4;
extern size_t size3d3_5;
extern size_t size3d3_6;
extern size_t size3d3_3;
extern int16 sign3dg;
extern uint8 g_theaterGrids[];
extern int16 g_unusedLoadDoneFlag;
extern char a_3d3[];
extern char aRb[];
extern char aOpenErrorOn_3d3[];
extern char aBadObjFileFormat_[];
extern char aObjectDataTooBig_[];
extern char aRb_0[];
extern char aPhoto_3d3[];
extern char aPleaseInsertF15DiskB[];
extern char aRb_1[];
extern char aPhoto_3d3_0[];
extern char aObjdataOverflow[];
extern char a_3dt[];
extern char aRb_2[];
extern char aOpenErrorOn_3dt[];
extern char aBadTileFileFormat_[];
extern char aTooManyTiles_[];
extern char aTooMuchTileData[];
extern char a_3dg[];
extern char aRb_3[];
extern uint8 aPleaseInsertScenarioD[];
extern char aPressKeyWhenReady[];
extern char aBadGridFileFormat_[];
extern int16 g_savedDivZeroVecOff;
extern int16 g_savedDivZeroVecSeg;
extern int16 g_clipP1xLo;
extern int16 g_clipP1xHi;
extern int16 g_clipP1yLo;
extern int16 g_clipP1yHi;
extern int16 g_clipP2xLo;
extern int16 g_clipP2xHi;
extern int16 g_clipP2yLo;
extern int16 g_clipP2yHi;
extern int16 g_clipMidxLo;
extern int16 g_clipMidxHi;
extern int16 g_clipMidyLo;
extern int16 g_clipMidyHi;
extern uint8 g_clipOutcode1;
extern uint8 g_clipOutcode2;
extern uint8 g_clipNeedsSubdiv;
extern int16 g_clipSavedxLo;
extern int16 g_clipSavedxHi;
extern int16 g_clipSavedyLo;
extern int16 g_clipSavedyHi;
extern int16 g_clipSaved2xLo;
extern int16 g_clipSaved2xHi;
extern int16 g_clipSaved2yLo;
extern int16 g_clipSaved2yHi;
extern int16 g_mapTileLodTable[];
extern int16 g_rleRowBase;
extern int16 g_horizonEdgeX;
extern int16 g_horizonNegPitch;
extern uint8 g_horizonSkyColor;
extern uint8 g_horizonGroundColor;
extern int16 g_horizonSideFlag;
/* colorLut: 256-entry 3D-shape colour-remap table; its low entries double as
 * the LOD/clip control words (threshold table, cull distance, near-clip
 * table) read by the projection code. See egdata.c. */
extern uint8 colorLut[];
/* Object-cull scale tables (word rows). */
extern int16 g_overlayBaseX[];
extern int16 g_overlayBaseY[];
extern int16 g_camTransXLo;
extern int16 g_camTransXHi;
extern int16 g_camTransYLo;
extern int16 g_camTransYHi;
extern int16 g_objRenderMode;
extern int16 g_rotSinYaw;
extern int16 g_rotCosYaw;
extern int16 g_viewRotMatrix[9];
/* Overlaid LZW-dict / vertex-projection scratch region; see struct VtxScratch.
 * C flight code uses vtxScratch.vproj. */
extern struct VtxScratch vtxScratch;
extern uint8 flt15_buf2[];
extern int16 g_objDirX;
extern int16 g_objDirY;
extern int16 g_objDirZ;
extern int16 g_rotInputX;
extern int16 g_vtxLoopEnd;
extern int16 g_vtxScale;
extern int16 g_primCoordPtr;
extern int16 g_primCountPtr;
extern int16 g_primDataBase;
extern uint8 g_primRunCount;
extern uint8 g_faceVtxCount;
extern uint8 g_vtxSlotPhase;
extern int16 g_clipVtxA0;
extern int16 g_clipVtxA1;
extern int16 g_clipVtxA2;
extern int16 g_clipVtxA3;
extern int16 g_clipVtxB0;
extern int16 g_clipVtxB1;
extern int16 g_clipVtxB2;
extern int16 g_clipVtxB3;
extern uint8 g_unusedClipFlag;
extern uint8 g_edgeRunCount;
extern int16 g_savedPrimVtxScale;
extern uint8 dacValues1[];
extern uint8 dacValues[];
extern uint8 g_dacGroundPalette[];
extern uint8 otherDacValues[];
extern uint8 g_dacGroundPaletteSrc[];
extern int16 g_sineTableBase;
extern int16 g_sineTableDelta;
extern int16 g_angleLut[];
extern uint8 g_clipSwapFlag;
extern int16 g_clipDeltaX;
extern int16 g_clipDeltaY;
extern int16 g_clipHalfDeltaX;
extern int16 g_clipHalfDeltaY;
extern int16 g_clipMaxX;
extern int16 g_clipMaxY;
extern int16 g_lineX1;
extern int16 g_lineX2;
extern int16 g_lineY1;
extern int16 g_lineY2;
extern int16 g_spanMinX[220];   /* per-scanline minimum (left) X edge, init 0xFFFF */
extern int16 g_spanMaxX[220];   /* per-scanline maximum (right) X edge, init 0 */
extern int16 g_rasterDeltaX;
extern int16 g_rasterDeltaY;
extern int16 g_dirtyRectMinY;
extern int16 g_dirtyRectMaxY;
extern uint8 g_rasterClipFlags;
extern int16 g_clipDivisorX;
extern int16 g_clipDivisorY;
extern int16 g_clipMidpointX;
extern int16 g_clipMidpointY;
extern uint8 cbreakHit;
extern int16 origCBreakSeg;
extern int16 origCBreakOfs;
extern uint8 g_frameSyncPending;
extern uint8 timerHandlerInstalled;
extern int16 g_timerElapsedLo;
extern int16 g_timerElapsedHi;
extern int16 g_timerCountdownTarget;
extern int16 g_timerReloadDivisor;
extern int16 g_timerTickCount;
extern int16 g_timerRunDivider;
extern uint8 g_timerDividerCounter;
extern int16 g_timerMode;
extern int16 g_timerCalSumLo;
extern int16 g_timerCalSumHi;
extern uint8 g_timerSyncToRetrace;
extern int16 g_timerTickCountdown;
extern int16 g_timerRetraceResult;
extern uint8 g_timerTickByte[0x21A];
extern int16 g_tapeText0Page;
extern int16 g_tapeText0X;
extern int16 g_tapeText0Y;
extern int16 g_tapeText0Font;
extern int16 g_tapeText0ClipTop;
extern int16 g_tapeText0ClipBottom;
extern int16 g_tapeText1Page;
extern int16 g_tapeText1X;
extern int16 g_tapeText1Y;
extern int16 g_tapeText1Font;
extern int16 g_tapeText1ClipX1;
extern int16 g_tapeText1ClipX2;
extern int16 g_tapeText2Page;
extern int16 g_tapeText2X;
extern int16 g_tapeText2Y;
extern int16 g_tapeText2Font;
extern int16 g_tapeText2ClipTop;
extern int16 g_tapeText2ClipX1;
extern int16 g_tapeText2ClipX2;
extern int16 g_tapeText3Page;
extern int16 g_tapeText3X;
extern int16 g_tapeText3Y;
extern int16 g_tapeText3Font;
extern int16 g_tapeSprite0BufPtr;
extern int16 g_tapeSprite0SrcY;
extern int16 g_tapeSprite0Page;
extern int16 g_tapeSprite0DstX;
extern int16 g_tapeSprite0DstY;
extern int16 g_tapeSprite0Width;
extern int16 g_tapeSprite0Height;
extern int16 g_tapeSprite1BufPtr;
extern int16 g_tapeSprite1SrcX;
extern int16 g_tapeSprite1SrcY;
extern int16 g_tapeSprite1Page;
extern int16 g_tapeSprite1DstX;
extern int16 g_tapeSprite1DstY;
extern int16 g_tapeSprite1Width;
extern int16 g_tapeSprite1Height;
extern int16 g_tapeSprite2BufPtr;
extern int16 g_tapeSprite2Page;
extern int16 g_tapeSprite3BufPtr;
extern int16 g_tapeSprite3Page;
extern uint8 g_headingBase;
extern int16 g_tapeOriginX;
extern uint8 g_tapeCursorBackShift;
extern int16 g_tapeTickPitch;
extern uint8 g_tapeScaleShift;
extern int16 g_speedTapeTickStep;
extern int16 g_altTapeTickStep;
extern int16 g_headingPixPerDeg;
extern int16 g_compassWrapLimit;
extern int16 g_headingModulus;
extern int16 g_headingWrapOffset;
extern uint8 g_halfScaleRender;
extern int16 g_altRemainder;
extern int16 g_compassScrollIdx;
extern int16 g_compassDrawX;
extern int16 g_tapeRenderX;
extern uint8 g_tapePageCounter;
extern uint8 g_hudDrawnFlag;
extern uint8 g_tapeRenderMode;
extern uint8 g_compassTapeBuf[];
extern uint8 g_tapeColumn;
extern uint8 g_tapeChar;
extern int16 g_tapeCursorX;
extern int16 g_tapeSegmentCount;
extern int16 g_tapeDrawStr;
extern int16 g_tapeDrawStrY;
extern int16 g_tapeRollOfsB0;
extern int16 g_tapeRollOfsB1;
extern int16 g_tapeRollOfsB2;
extern int16 g_tapeRollOfsB3;
extern int16 g_tapeRollOfsA0;
extern int16 g_tapeRollOfsA1;
extern int16 g_tapeRollOfsA2;
extern int16 g_tapeRollOfsA3;
extern uint8 joyData[];
extern int16 g_joyCountX;
extern int16 g_joyCountY;
extern uint8 joyAxes[];
extern uint8 g_joyRawX;
extern uint8 g_joyRawY;
extern uint8 g_kbdActiveScan;
extern int16 g_kbdLastTick;
extern uint8 g_kbdPrevScan;
extern uint8 g_kbdLastDirKey;
extern uint8 g_kbdDelayCounter[];
extern uint8 aLandingGearRaised[];
extern uint8 aBrakesOn[];
extern uint8 a_[];
extern uint8 aG[];
extern uint8 g_rollGeeTable[];
extern int16 g_orientMatrix[];
extern int16 g_yawMatrix[9];
extern int16 g_pitchMatrix[9];
extern int16 g_rollMatrix[9];
extern int16 g_matrixScratch[];
extern int g_ourHead;
extern int g_ourPitch;
extern int g_ourRoll;
extern int16 g_viewZ;
extern unsigned int g_altitude;
extern char g_orientationDirty;
extern int16 g_setThrust;
extern int16 g_joyCalibTimer;
extern char a256left_pic[];
extern char a256right_pic[];
extern char a256rear_pic[];
extern char aLeft_pic[];
extern char aRight_pic[];
extern char aRear_pic[];
extern int16 g_hudBottomY;
extern int16 g_rearViewShape[];
extern int16 g_lastViewKey;
extern uint8 aFiring[];
extern uint8 aFiredBy[];
extern char aTakingOff[];
extern char aDash[];
extern char aColon[];
extern uint8 aEmpty_5950[];
extern uint8 aMisses[];
extern uint8 aDestroyedBy[];
extern uint8 aDestroyedBy_0[];
extern uint8 aGroundImpact[];
extern uint8 aHitBy[];
extern uint8 aIneffective[];
extern uint8 aHitBy_0[];
extern int16 ammoNumX[];
extern char aSecond_Target[];
extern char aPrimaryTarget_0[];
extern char a0[];
extern char aFired[];
extern int16 g_tacmapIndicators[];
extern int16 g_viewportDescFront[];
extern int16 *g_pageFront;
extern int16 g_viewportDescMid[];
extern int16 *g_pageBack;
extern int16 g_viewportDescBack[];
extern int16 *g_pageOffscreen;
extern int16 g_mapZoomLevel;
/* g_viewZU: unsigned view of g_viewZ (same storage). In the asm build this is
   the linker alias _g_viewZU EQU _g_viewZ; with NO_ASM there is no asm to carry
   the alias, so reinterpret g_viewZ's bytes directly. */
#ifdef NO_ASM
#define g_viewZU (*(uint16 *)&g_viewZ)
#else
extern uint16 g_viewZU;
#endif
extern char g_rollWasNonzero;
extern int16 g_rotationCounter;
extern int16 g_lastSpawnTick;
extern int16 g_radarScopeRange;
extern int16 g_mapCenterX;
extern int16 g_mapCenterY;
extern int16 radarRange;
extern int16 g_hudMsgTimer;
extern int16 g_dirMsgTimer;
extern char aStallWarning[];
extern char aAccel[];
extern char aTraining[];
extern char aAutopilot[];
extern char aPressAnyKeyToP[];
extern uint8 aTac[];
extern char aTrackcam[];
extern char aAhead[];
extern char aRear[];
extern char aRight[];
extern char aLeft[];
extern char aMap[];
extern uint8 aDestroyedByGun[];
extern uint8 aHitByGunfire[];
extern uint8 aDestroyedByG_0[];
extern char aAt_0[];
extern uint8 aPrimaryTarget[];
extern uint8 aSecondaryTarget[];
extern uint8 aNoTarget[];
extern uint8 aNoTarget_0[];
extern char aMissileLock[];
extern char aRange[];
extern char aDot[];
extern char aKm[];
extern char a_3d3_0[];
extern char aRb_4[];
extern char aOpenErrorOn_3d3_0[];
extern uint8 g_extraScaleShift;
extern char a15flt_xxx[];
extern char aBrg[];
extern uint8 aLong[];
extern uint8 aMedium[];
extern uint8 aShort[];
extern uint8 aRangeRadar[];
extern uint8 aDetailLevel[];
extern uint8 aKybdSensitivit[];
extern uint8 aMemoryAvailabl[];
extern uint8 aJiffiesFrame[];
extern uint8 aSounds[];
extern uint8 aDirector[];
extern uint8 aOff[];
extern uint8 aWaypointPrimar[];
extern uint8 aWaypointSecond[];
extern uint8 aWaypointFriend[];
extern uint8 aAutopilotOff[];
extern uint8 aAutopilotOn[];
extern int16 g_axisInputAccum[];
extern uint8 aNotAvailable[];
extern uint8 aArmed[];
extern int16 voiceCueThresholds[];
extern uint8 g_exitMsgDigit;
extern uint8 g_exitMsgTerm;
extern uint8 picBuf[];
extern uint8 aFileNotFound[];
extern uint8 aNoFileBuffersAvailabl[];
extern uint8 aOpenError[];
extern uint8 aFileClosingError[];
extern uint8 aReadError[];
extern uint8 aWriteError[];
extern int16 fileReadPos;
extern int16 tmpFileHandle;
extern uint8 picDecodedRowBuf[];
extern int16 g_picBlitBytesRemaining;
extern int16 picPageIndex;
extern int16 picRowOffset;
extern int16 g_picBlitCurrentRow;
extern int16 picReadFromFilePtr;
extern uint8 far *farPointer;
extern int16 flt15HeaderWord;
extern uint8 flt15_buf1[];
extern size_t flt15_size;
extern int16 g_picLookupResult;
extern int16 g_picByte;
extern uint8 g_picNumberDictSlots;
extern uint8 g_picFileWord;
extern int16 g_picByteUnsignedFlag;
extern int16 g_unusedFrameVal;
extern int g_scopeArcColor;
extern char strBuf[];
extern uint8 g_strTruncDot;
extern uint8 g_strTruncTerm[];
extern int16 g_rollPitchTrim;
extern int16 g_sphereTiltZ;
extern int16 g_scopeCenterX;
extern int16 g_scopeCenterY;
extern int16 g_extViewPitch;
extern uint8 g_geeStringBuf[];
extern int g_gees;
extern int g_detailLevel;
extern int16 g_autoCrashDive;
extern int16 g_missionTick;
extern uint8 far *g_floppyMotorPtr;
extern FILE *fileHandle;
extern int16 g_gunFiredFlag;
extern int16 g_damageTakenFlag;
extern int16 g_threatRefHead;
extern int16 g_nearestThreatRange;
extern struct Game far *gameData;
extern int16 g_finalThreatScore;
extern int16 g_tileEntryCount;
extern int16 g_targetEntityCount;
extern int16 g_attackRangeX;
extern uint8 buf4_3dg[];
extern int16 g_playerPlaneFlags;
extern int16 g_attackRangeY;
extern uint8 buf3_3dg[];
extern int16 g_targetInHudFlag;
extern int16 g_lockedTargetKilled;
extern int g_hitEffectTimer;
extern uint8 buf2_3dg[];
extern struct TileObject* g_nearestTileObj;
extern uint8 buf1_3dg[];
extern char g_savedPosVisible;
extern int16 g_threatDisplayTtl;
extern uint8 buf_3dt[]; // #define MAX_TILE_DATA
extern int16 g_stallSpeed;
extern uint8 g_topLodGrid[];
extern int16 g_lastMissileSlot;
extern int g_velocity;
extern int16 g_enemyThreatCount;
extern int16 g_camRotMatrix[];
extern struct ViewSnapshot g_viewSnapshotRing[];
extern int16 g_knots;
extern struct GroundTargetTable g_planeTable;
extern int16 g_unusedViewXSnap;
extern uint8 buf3d3_1[];
extern int16 g_bulletTrackCount;
extern int16 g_thrust;
extern int16 g_northSouthSign;
extern int16 g_unusedViewYSnap;
extern uint8 g_mapCellFlags[];
extern int16 g_threatTimerInit;
extern uint8 buf3d3_2[];
extern struct TargetSlot g_targetSlots[];
extern uint8 buf3d3_3[];
extern int32 g_camEyeX;
extern struct SimObject g_simObjects[];
extern int16 g_aamLockCooldown;
extern int32 g_camEyeY;
extern int16 g_threatRefX;
extern int16 g_liftForce;
extern int16 g_wreckFallVel;
extern int16 g_camEyeZ;
extern int16 g_threatRefY;
extern uint8 hercFlag;
extern int16 g_viewRoll;
extern struct DynTileOverride g_dynTileEntries[]; // overlaps the following bytes with structs
extern int16 g_threatRefZ;
extern int32 g_ViewX;
extern int16 g_savedSamTtl;
extern struct TileObject nearestTile;
extern int32 g_ViewY;
extern struct ReplayLog g_replayLog;
extern int16 g_ejectState;
extern uint8 g_modelVertY[];
extern int16 g_scopeArcRange;
extern uint8 g_modelVertZ[];
extern int16 keyValue;
extern int16 g_waypointBearing;
extern int g_viewPitch;
extern int16 g_threatLabelTarget;
extern int16 g_skyColorIndex;
extern int16 g_sphereRingRadii[];
extern int16 g_hitMapX;
extern int16 g_groundAltitude;
extern int16 g_viewX_;
extern int16 g_wreckX;
extern uint8 g_waterTargetId[];
extern int16 g_hitMapY;
extern int16 sign3d3;
extern int16 g_initPhase;
extern int16 g_hitAlt;
extern int16 g_viewY_;
extern int16 g_planeCount;
extern int16 g_unusedEventHist0;
extern int16 g_wreckY;
extern uint8 g_tileKillTally[];
extern int16 g_scopeArcStart;
extern int16 g_scopeArcEnd;
extern char tempString[80];
extern int16 g_gunHits;
extern union REGS regs;
extern uint8 g_biosPixelPage;
extern int16 g_biosPixelX;
extern int16 g_biosPixelY;
extern int16 g_unusedEventHist1;
extern int16 g_wreckAlt;
#define UNIT_STATE_COUNT 0x64
extern uint8 g_shapeTargetCategory[UNIT_STATE_COUNT];
extern int16 g_flightPathMarkerY;
extern int16 g_aamLockActive;
extern int16 g_unusedSavedWord;
extern int g_rollInput;
extern int16 flagFarToNear;
extern int16 keyScancode;
extern int16 g_unusedEventHist2;
extern int16 g_projDepth;
extern int16 g_scopeClipLeft;
extern int16 g_scopeClipTop;
extern int32 g_viewTargetX;
extern int16 g_loftTargetIdx;
extern int32 g_viewTargetY;
extern int16 g_crashCamX;
extern uint8 g_landTargetId[];
extern int16 g_viewTargetAlt;
extern int16 g_viewTargetObj;
extern char g_itoaScratch[];
extern int16 g_crashCamY;
extern int16 g_prevScopeRange;
extern int16 g_crashCamZ;
extern int16 g_tileZoomShift;
extern int16 g_enemyAirRemaining;
extern int16 g_groundUnitCount;
extern int16 g_enemyGroundRemaining;
extern char string_3C04A[80];
extern int16 g_mapMode;
extern int16 g_enemyAlertFlag;
extern int16 g_activePanelMode;
extern int16 g_targetLeadAngle;
extern char* g_targetNameTable[];
extern int16 g_closestThreatIndex;
extern int16 g_curLod;
extern char g_stringPool[];
extern int16 g_currentWeaponType;
extern int16 g_scopeClipRight;
extern struct TileSceneObject *matrix3dt_2[5][32];
extern char g_drawPage;
extern int16 g_scopeClipBottom;
extern int16 g_pitchInput;
extern int16 g_cornerSpeed;
extern struct TileSceneObject *g_curTileEntry;
extern int16 g_viewHeading;
extern int16 *g_overlayCenterX;
extern int16 g_planeScanCount;
extern uint8 g_highGeeFlag[];
extern int16 *g_overlayCenterY;
extern int16 g_aamSeekerX;
extern struct GameComm far *commData;
extern int16 g_threatRadarFlag;
extern int16 g_aamSeekerY;
extern int g_jiffiesPerFrame;
extern uint8 g_missionEndedFlag[];
extern int16 g_viewHeadingOffset;
extern int16 gfxBufPtr;
extern int16 g_climbRate;
extern struct Proj3d g_proj3d;
extern size_t size3d3_7;
extern int16 g_viewPosX;
extern int16 g_viewPosY;
extern int8 g_targetCompatTable[];
extern int16 g_viewPosZ;
extern char *g_mapTerrainMode;
extern uint16 g_frameTimingAccum;
extern int16 g_offscreenProjX;
extern int16 *g_viewParams;
extern int16 g_sphereRadius;
extern int16 g_sphereDistZ;
extern int16 g_spherePitch;
extern int16 g_sphereRoll;
extern int16 g_frameSyncWait;
extern int16 g_kbdSensitivity;
extern int16 g_fireCooldown;
extern int16 g_objColorBase;
extern int16 g_eventLogCount;
extern int16 g_objLocalX;
extern int16 g_objLocalY;
extern int16 g_objLocalZ;
extern int16 g_tileEntryIdx;
extern int16 g_tileWorldSize;
extern int16 g_tileGridDim;
extern int16 g_mapOriginX;
extern int16 g_mapOriginY;
extern int16 g_threatSpec;
extern int16 g_activeThreatCount;
extern int16 g_acqRange;
extern int16 g_acqAimY;
extern int16 g_lockToneFlag;
extern int16 g_targetRange;
extern int16 g_unusedHudFlag;
extern int16 g_targetBearing;
extern int16 g_prevKillMarker;
extern int16 g_aamLeadDist;
extern int16 g_axisInput1;
extern int16 *g_targetViewParams;
extern int16 g_trkRange;
extern int16 g_trkBearing;
extern int16 g_trkSize;
extern int16 g_trkScale;
extern int16 g_trkPitch;
extern int16 g_trkRoll;
extern int16 g_rngSeed;
extern uint16 g_wingmanX;
extern uint16 g_wingmanY;
extern uint8 g_objShade;
extern int16 g_lodDistBase;
extern int16 g_lodDistScale;
extern int16 g_lodDistNear;
extern int16 g_lodDistFar;
extern char far *g_modelStreamPtr;
extern int16 g_objRelX;
extern int16 g_objRelY;
extern int16 g_objTransform[4];
extern uint8 g_objHasRotation;
extern int16 g_objDistance;
extern int16 g_modelVtxCount;
extern int16 g_modelEdgeCount;
extern int16 g_modelWideVtxFlag;
extern int16 g_vtxSignMaskLo;
extern int16 g_vtxSignMaskHi;
extern int16 g_sortedObjCount;
extern int16 g_spinAngle;
extern int16 g_posVisibleFlag;
extern uint8 g_offscreenRender;
extern int16 g_modelEvenOddBit;
extern int16 g_mapLodIndex;

#if defined(MSDOS)
extern int rand();
#endif
extern long _aNlmul(long, long);

#endif // F15_SE2_EGAME
