#ifndef F15_SE2_START
#define F15_SE2_START
#include "inttype.h"
#include "struct.h"
#include "comm.h"
#include "pointers.h"

#include <stdio.h>
#include <dos.h>

#define __int32 long
#define __int8 char
#define __cdecl
#define __far far
#define COMM_SNDOVL_NAME 0xd
#define ROSTER_SCORE_LO 0x16
#define OVL_HDR_CODESEG 0x18
#define ROSTER_SCORE_HI 0x18
#define COMM_GVXOVL_SEG 0x1a
#define ROSTER_LASTSCORE 0x1a
#define COMM_SNDOVL_SEG 0x1c
#define OVL_HDR_FIRSTIDX 0x1c
#define ROSTER_UNK1 0x1c
#define ROSTER_UNK2 0x1d
#define COMM_MISCOVL_SEG 0x1e
#define OVL_HDR_SIZE1 0x1e
#define ROSTER_THEATER 0x1e
#define ROSTER_DIFFICULTY 0x1f
#define COMM_GFXBUF_PTR 0x20
#define OVL_HDR_SIZE2 0x20
#define GAMEDATA_UNK2 0x20
#define OVL_HDR_SLOTCOUNT 0x22
#define COMM_SETUP1 0x22
#define GAMEDATA_UNK3 0x22
#define OVL_HDR_FIRSTPTR 0x24
#define COMM_HERC_FLAG 0x24
#define COMM_SETUPDONE 0x26
#define COMM_UNK2 0x28
#define COMM_UNK3 0x2c
#define GAMEDATA_LASTSCORE 0x2e
#define COMM_SETUP_GFXMODE 0x30
#define COMM_BUFFER_FLAG2 0x30
#define GAMEDATA_SCORE_LO 0x32
#define GAMEDATA_SCORE_HI 0x34
#define GAMEDATA_THEATER 0x38
#define COMM_UNK7 0x38  /* weaponType */
#define GAMEDATA_FLAG4 0x3a
#define COMM_UNK5 0x3a
#define GAMEDATA_FLAG3 0x3c
#define COMM_UNK6 0x3c
#define COMM_BUFFER_DIFFICULTY 0x3e
#define SEGMENT_BDA 0x40
#define COMM_UNK8 0x40  /* weaponCount */
#define COMM_BUFFER_RAND 0x42
#define GAMEDATA_UNK1 0x44
#define COMM_JOYDATA_OFF 0x48
#define COMM_BUFFER_FLAG1 0x4e
#define COMM_USEJOY_OFF 0x72
#define COMM_GFXMODE_OFFSET 0x78
#define TIMEOUT_MPS 0x78
#define BDA_EGASW 0x88
#define TIMEOUT_ADV 0xb4
#define BDA_CRTC 0x463
#define DOS_PRINT_STR 0x9
#define DOS_ERROR_RMDIR 0x10
#define DOS_SET_IRQH 0x25
#define DOS_ALLOC_MEM 0x48
#define IRQ_PIT 0x8
#define IRQ_VIDEO 0x10
#define IRQ_KBD 0x16
#define IRQ_TIME 0x1a
#define IRQ_CBREAK 0x1b
#define HALLFAME_RECORDSZ 0x20
#define IRQ_DOS 0x21
#define PORT_PIT_TIME0 0x40
#define PORT_PIT_CNTRL 0x43
#define SCREEN_MAXY 0xc7
#define SCREEN_MAXX 0x13f
#define FILE_READBUF_SIZE 0x200
int checkQuitFlag();
void initGraphics(void);
int setargv();
int setenvp();
void clearKeybuf(void);
void waitJoyKey(void);
int joyOrKey();
void waitMdaCgaStatus(int16);
void drawLine(int16 *pageNum, int x1, int y1, int x2, int y2, int color);
void showPic640(char *filename);
void missionSelect(void);
int __cdecl missionMenuSelect(char **names, char **desc, char *title, int s);
void animateArm(int, int);
int askRepeatMission(void);
void checkDiskA(void);
void missionDecode(void);
void printMission(void);
int pollMenuInput();
void clearBriefing(void);
void __cdecl showSprite(int, int, int, int, int, int, int);
int dead_drawWrappedText();
int unreach_1130B();
int sub_11458();
void seedRandom();
int __cdecl randMul(uint16);
int sub_118B9();
int sub_118D1();
int far timerIrqHandler();
void timerIrqCallback();
void calibrateTimerSpeed();
int manipulateTimer();
void increaseTimerCounters();
int doFcbSearch();
void picBlit(int handle, int unk);
void pilotSelect(int16 ps_needSplash);
void updateHallfame();
void displayPilots(void);
void __cdecl printPilot(int);
void processPilotInput();
void blinkPilot();
void __cdecl gameDataToPilot(struct Pilot *pilot);
void pilotToGameData(uint8 *pilotData);
void __cdecl pilotNameInput(int16 *, int, int, int, struct Pilot *);
void loadHallfame(void);
void saveHallfame();
int getJoyKey();
int readInputKey();
int sub_12652();
int sub_12660();
int sub_12680();
int sub_126CB();
int sub_126E2();
int mystrlen(const char* str);
void mystrcat(char *dst, char *src);
int sub_12741();
void nearmemset(void *dst, char value, int count);
void farmemset(char far *dst, char value, int count);
int my_memcpy();
int unreach_127AE();
int sub_127CA();
int myItoa();
int base10_itoa();
int base16_itoa();
int base2_itoa();
int unreach_1292C();
void dos_printstring(const char *str);
int loadOverlay(const char *filename);
int unreach_12AE1();
int sub_12B1B();
void __cdecl clearRect(int16 *buf, int x, int y, int maxx, int maxy);
int unreach_12C59();
int sub_12C6F();
void clearDirtyRects();
void drawLineWrapper();
void clipAndDrawLine();
int computeOutcode();
int far sub_12F8B();
int getInterruptHandler();
int far cbreakHandler();
int unreach_12FFC(int filename, int a);
int unreach_13032(int filename, int a, int b);
int unreach_1306A();
int unreach_130B4();
int unreach_130D4();
int unreach_130E8();
int unreach_13100();
int unreach_13171();
void fileClose(int handle);
int unreach_131EA();
int unreach_13215();
int unreach_13243();
int read512FromFileIntoBuf();
int unreach_1328D();
int writeFileAtRaw();
int unreach_1333E(int filename, int a);
void unreach_loadPicAt();
int unreach_13442();
int unreach_134AA();
void decodePic(int handle, int segment);
void nullsub_1();
void decodePicRow();
void picReadDataAndMakeDict();
void picMakeDict();
void doPicDecode();
int dictionaryLookup();
uint16 __cdecl allocBuffer(int sz);
int unreach_freeBuffer(int freeSeg);
uint16 __cdecl dos_alloc(int sz);
int unreach_dos_freeMem(int freeSeg);
int16 *__cdecl findNearestTerrain(__int32, __int32);
unsigned __int32 __cdecl scaleCoordByLevel(int, unsigned __int32);
int __cdecl lookupGridCell(int16, int16, int16);
void parseGridTerrain(void);
void parseTerrain(char *dest);
void parseGrid();
int __cdecl showMsgWaitKey(const char *);
void replaceExtension(char *dest, char *source);
int unreach_13ED2();
int unreach_13F08();
int unreach_initPicDictionary();
int unreach_13F52();
int unreach_13F6A();
int unreach_14009();
void missionGenerate(void);
void runGenerator();
int __cdecl findOrPlaceItem(int, int, int);
int __cdecl itemDistance(int, int);
void __cdecl positionUnit(int, int);
int __cdecl approxDistance(int, int);
void __cdecl parseWorld(const char *);
void exportWorldToComm(const char *filename);
void doNothing2(const char *msg, int a, int b, int c);
int __cdecl calcBearing(int, int);
int setMoveDstComm7A(const char *filename, const char* arg_1);
int unreach_15285();
void memAppend(void *ptr, int itemsz, int count, FILE* unused);
void doNothing(FILE*);
char *__cdecl getItemCoordStr(int16);
char *__cdecl formatGridRef(int16, int16, int16);
int __cdecl clampValue(int, int, int);
void __cdecl buildTargetLabel(int arg_0);
int sub_15741();
int sub_15750();
int sub_15F0A();
int sub_164C0();
int sub_16A06();
int unreach_16A6C();
void far pollJoystick();
void readJoyPort();
void normalizeJoyAxis();
void far copyJoystickData(uint8 FAR *ptr);
extern uint8 crt0_start[];
extern int16 crt0_16B52;
extern uint8 byte_16B54[];
extern uint8 unk_16B56;
extern uint8 unk_16B57;
extern uint8 aMsRunTimeLibra[];
extern uint8 unk_16B90;
extern uint8 crt0_end;
extern char aLabs_pic[];
extern char aAdv_pic[];
extern char aEgraphic_exe[];
extern char aTitle640_pic[];
extern char aTitle16_pic[];
extern char aF15_spr[];
extern char aF15_spr_0[];
extern char aTemp_wld[];
extern int16 bufPageDesc;
extern uint8 unk_16BF0[];
extern int16 *bufPtr;
extern uint8 unk_16C10[];
extern uint8 aLibya[];
extern uint8 aPersianGulf[];
extern uint8 aVietnam[];
extern uint8 aMiddleEast[];
extern uint8 aOtherAreas[];
extern uint8 aAcrossTheLineO[];
extern uint8 aKeepingTheSeaL[];
extern uint8 aAmericaSLonges[];
extern uint8 aEaglesVsMigs[];
extern uint8 aInsertYourScen[];
extern uint8 aRookie[];
extern uint8 aPilot[];
extern uint8 aVeteran[];
extern uint8 aAce[];
extern uint8 aDemo[];
extern uint8 aGetOffToAGoodS[];
extern uint8 aForTheCasualPl[];
extern uint8 aForMoreSerious[];
extern uint8 aTheUltimateCha[];
extern uint8 aLetSSeeWhatThi[];
extern uint8 aNc[];
extern uint8 aCe[];
extern uint8 aJp[];
extern uint8 aNa[];
extern uint8 aNorthCape[];
extern uint8 aCentralEurope[];
extern uint8 aDesertStorm[];
extern uint8 aNorthAtlantic[];
extern uint8 aOtherAreas_0[];
extern uint8 aIntoTheSovietS[];
extern uint8 aRedStormRaging[];
extern uint8 aTheFightForKuw[];
extern uint8 aDefendingTheIc[];
extern uint8 aSelectABuiltIn[];
extern uint8 aHistoricalMiss[];
extern uint8 aGeneralAirStri[];
extern uint8 emptyMissTypeNames[];
extern uint8 aReenactHistory[];
extern uint8 aTheCoreOfTheAi[];
extern uint8 emptyMissTypeDescs[];
extern uint8 aSaddamSEyes[];
extern uint8 aCommandAndCont[];
extern uint8 aScudBusting[];
extern uint8 aNoNukes[];
extern uint8 aMoreHistorical[];
extern uint8 aIraqSEarlyWarn[];
extern uint8 aIraqiDefenseNe[];
extern uint8 aStopSaddamSTer[];
extern uint8 aNuclearResearc[];
extern uint8 emptyHistDesc1;
extern uint8 aBabyMilkFactory[];
extern uint8 aStopTheSpill[];
extern uint8 aBridgesToNowhe[];
extern uint8 aRepublicanGuar[];
extern uint8 aMoreHistoric_0[];
extern uint8 aChemicalBiolog[];
extern uint8 aSeverTheOilPum[];
extern uint8 aSaddamSEliteAr[];
extern uint8 aCutTheSupplyLi[];
extern uint8 emptyHistDesc2;
extern uint8 aMission[];
extern uint8 placeholder_3d3[];
extern char aWall_pic[];
extern char aDifficulty[];
extern char aTheater[];
extern char aRb_1[];
extern char aNoScenarioFile[];
extern char aSeeTechnicalSu[];
extern char aTheater_0[];
extern char aMissionType[];
extern struct PageDesc page1Desc;
extern int16 *page1NumPtr;
extern struct PageDesc page2Desc;
extern int *page2NumPtr;
extern struct PageDesc page3Desc;
extern uint8 unk_170B2[];
extern uint8 unk_170C0[];
extern char *missTheaNames[];
extern char *missTheaDesc[];
extern char *missDiffLevels[];
extern char *missDiffDesc[];
extern char *scenarioCodePtr[];
extern char *missScenarioNames[];
extern char *missScenarioDesc[];
extern char *missTypeNames[];
extern char *missTypeDesc[];
extern char *missHistorical1Names[];
extern char *missHistorical1Desc[];
extern char *missHistorical2Names[];
extern char *missHistorical2Desc[];
extern char *missionStr;
extern int16 armSrcX[];
extern int16 armSrcY[];
extern int16 armBlitX[];
extern int16 armBlitY[];
extern int16 armBlitW[];
extern int16 armBlitH[];
extern int16 enableHighlight;
extern char *plh3d3Ptr;
extern int16 missionPick;
extern int16 armSpriteIndex[];
extern char aRepeatLastMiss[];
extern char aRb_2[];
extern char aF15_spr_1[];
extern char aPleaseReinsert[];
extern char aPressSelectorW[];
extern char aDecodingMissio[];
extern char aTodaySMission[];
extern char aTakeoffFrom[];
extern char aOnc_2[];
extern char aPrimaryTarget[];
extern char aOnc_0[];
extern char aSecondaryTarge[];
extern char aOnc_1[];
extern int16 joyRepeatFlag;
extern struct SpriteParams spriteParams;
extern uint8 timerFlag;
extern uint8 timerHandlerInstalled;
extern int16 timerCountLo;
extern int16 timerCountHi;
extern int16 timerTarget;
extern int16 timerDivisor;
extern int16 timerTickCnt;
extern int16 timerReload;
extern uint8 timerDivider;
extern int16 timerMode;
extern int16 timerCalSumLo;
extern int16 timerCalSumHi;
extern uint8 timerSyncRetrace;
extern int16 timerTick;
extern int16 timerRetrace;
extern uint8 timerCounter;
extern uint8 timerCounter2;
extern uint8 timerCounter3;
extern uint8 timerCounter4;
extern uint8 unk_172C5;
extern uint8 fcbMatchStr[];
extern uint8 unk_172CA[];
extern uint8 searchFCB[];
extern uint8 diskTransferArea[];
extern int16 picCurrentRow;
extern uint8 a2ndLt_[];
extern uint8 a1stLt_[];
extern uint8 aCapt_[];
extern uint8 aMajor[];
extern uint8 aLtCol_[];
extern uint8 aColonel[];
extern uint8 aGen_[];
extern char aArmpiece_pic[];
extern char aHiscore_pic[];
extern uint8 pilotSelectFlag;
extern struct PageDesc screenDesc;
extern int16 *screenBuf;
extern struct PageDesc pageNumPageDesc;
extern int16 *pageNumPtr;
extern char *ranks[];
extern uint8 medalSpriteX[];
extern uint8 medalSpriteY[];
extern uint8 medalWidth[];
extern char aOriginalDiskIn[];
extern char aPressAKeyToCon[];
extern char aUseSelectorToC[];
extern char strOpenParen[];
extern char strCloseParen[];
extern int16 blinkColors[];
extern int16 blinkColorIdx;
extern char aMenterYourName[];
extern int16 pilotNameInputColors[];
extern char aRb_3[];
extern char aHallfame[];
extern char aWb[];
extern char aHallfame_0[];
extern int16 ovlSeg1;
extern int16 ovlParCnt;
extern int16 ovlParBlock;
extern int16 ovlSeg2;
extern uint8 ovlInsaneFlag;
extern uint8 aAlloc1M[];
extern uint8 aDosLied[];
extern uint8 aFileNFound[];
extern uint8 aEnoughMem[];
extern uint8 aOvlFail[];
extern uint8 aOvlOvrrun[];
extern uint8 aOvlShrink[];
extern uint8 aOvlRel[];
extern uint8 jmp_gfx_slot_0_alloc[];
extern uint8 jmp_gfx_slot_01[];
extern uint8 jmp_gfx_slot_02[];
extern uint8 jmp_gfx_slot_03[];
extern uint8 jmp_gfx_slot_04[];
extern uint8 jmp_gfx_slot_05_t04[];
extern uint8 jmp_gfx_slot_06[];
extern uint8 jmp_gfx_slot_07[];
extern uint8 jmp_gfx_slot_08[];
extern uint8 jmp_gfx_slot_09[];
extern uint8 jmp_gfx_slot_0a[];
extern uint8 jmp_gfx_slot_0b[];
extern uint8 jmp_gfx_slot_0c[];
extern uint8 jmp_gfx_slot_0d_setCurBuf[];
extern uint8 jmp_gfx_slot_0e_setCurBuf[];
extern uint8 jmp_gfx_slot_0f_getButPtr[];
extern uint8 jmp_gfx_slot_10_getCurBuf[];
extern uint8 jmp_gfx_slot_11[];
extern uint8 jmp_gfx_slot_12[];
extern uint8 jmp_gfx_slot_13[];
extern uint8 jmp_gfx_slot_14[];
extern uint8 jmp_gfx_slot_15[];
extern uint8 jmp_gfx_slot_15[];
extern uint8 jmp_gfx_slot_17[];
extern uint8 jmp_gfx_slot_18[];
extern uint8 jmp_gfx_slot_18[];
extern uint8 jmp_gfx_slot_1a[];
extern uint8 jmp_gfx_slot_1b[];
extern uint8 jmp_gfx_slot_1c[];
extern uint8 jmp_gfx_slot_1d[];
extern uint8 jmp_gfx_slot_1e[];
extern uint8 jmp_gfx_slot_1f[];
extern uint8 jmp_gfx_slot_20_setVal[];
extern uint8 jmp_gfx_slot_21[];
extern uint8 jmp_gfx_slot_22_nullsub[];
extern uint8 jmp_gfx_slot_22_nullsub[];
extern uint8 jmp_gfx_slot_24[];
extern uint8 jmp_gfx_slot_25[];
extern uint8 jmp_gfx_slot_26[];
extern uint8 jmp_gfx_slot_27[];
extern uint8 jmp_gfx_slot_25[];
extern uint8 jmp_gfx_slot_29_fillRect[];
extern uint8 jmp_gfx_slot_2a[];
extern uint8 jmp_gfx_slot_2b[];
extern uint8 jmp_gfx_slot_2c_blitPage1[];
extern uint8 jmp_gfx_slot_2d[];
extern uint8 jmp_gfx_slot_2e[];
extern uint8 jmp_gfx_slot_2f[];
extern uint8 jmp_gfx_slot_30_blitToCurrent[];
extern uint8 jmp_gfx_slot_31[];
extern uint8 jmp_gfx_slot_32[];
extern uint8 jmp_gfx_slot_33_memcpyRow[];
extern uint8 jmp_gfx_slot_33_memcpyRow[];
extern uint8 jmp_gfx_slot_35_null[];
extern uint8 jmp_gfx_slot_36_null[];
extern uint8 jmp_gfx_slot_37_null[];
extern uint8 jmp_gfx_slot_38_getBuf[];
extern uint8 jmp_gfx_slot_39[];
extern uint8 jmp_gfx_slot_3a_getRowOffset[];
extern uint8 jmp_gfx_slot_3b_clearBuf[];
extern uint8 jmp_gfx_slot_3c_setMode13[];
extern uint8 jmp_gfx_slot_3d_null[];
extern uint8 jmp_gfx_slot_3e[];
extern uint8 jmp_gfx_slot_3f_ax3[];
extern uint8 jmp_gfx_slot_40[];
extern uint8 jmp_gfx_slot_41[];
extern uint8 jmp_gfx_slot_42[];
extern uint8 jmp_gfx_slot_43[];
extern uint8 jmp_gfx_slot_44_setDac[];
extern uint8 jmp_gfx_slot_45_retrace[];
extern uint8 jmp_gfx_slot_46_retrace2[];
extern uint8 jmp_gfx_slot_13[];
extern uint8 jmp_gfx_slot_14[];
extern uint8 jmp_gfx_slot_11[];
extern uint8 jmp_gfx_slot_12[];
extern uint8 jmp_gfx_slot_4b_storeBufPtr[];
extern uint8 jmp_gfx_slot_4c[];
extern uint8 jmp_gfx_slot_4d[];
extern uint8 jmp_gfx_slot_4e_getVal[];
extern uint8 jmp_gfx_slot_4f[];
extern uint8 jmp_gfx_slot_50_null[];
extern uint8 jmp_gfx_slot_51_null[];
extern uint8 jmp_gfx_slot_52[];
extern uint8 jmp_gfx_slot_52_null[];
extern uint8 jmp_misc_5a_checkKeyBuf[];
extern uint8 jmp_misc_5b_getKey[];
extern uint8 jmp_misc_5c_dosGetKey[];
extern uint8 jmp_misc_5d_readJoy[];
extern uint8 jmp_misc_5e_5f_clearKeyFlags[];
extern uint8 jmp_misc_5e_5f_clearKeyFlags[];
extern uint8 unk_177EC[];
extern uint8 unk_177F6[];
extern uint8 jmp_0[];
extern uint8 jmp_0[];
extern uint8 jmp_0[];
extern uint8 jmp_0[];
extern uint8 unk_17810[];
extern uint8 unk_17812;
extern uint8 unk_17813;
extern uint8 unk_17814;
extern uint8 unk_17815;
extern uint8 unk_17816[];
extern uint8 jmp_0[];
extern uint8 jmp_0[];
extern int16 joyMinValues;
extern int16 joyMaxValues;
extern int16 joyCenterValues;
extern int16 joyRangeBelow;
extern int16 joyRangeAbove;
extern int16 joyRawAxis0;
extern int16 joyRawAxis1;
extern uint8 joyAxes[];
extern int16 clearRectX;
extern int16 clearRectY;
extern int16 clearRectWidth;
extern int16 clearRectHeight;
extern int16 lineX1;
extern int16 lineX2;
extern int16 lineY1;
extern int16 lineY2;
extern uint8 dirtyMinBuf[];
extern uint8 dirtyMaxBuf[];
extern uint8 unk_17B04[];
extern uint8 byte_17B06[];
extern int16 word_17BE7;
extern int16 word_17BE9;
extern int16 dirtyRectMin;
extern int16 dirtyRectMax;
extern uint8 clipOutcode;
extern int16 clipDx;
extern int16 clipDy;
extern int16 clipDxHalf;
extern int16 clipDyHalf;
extern int16 clipMaxX;
extern int16 clipMaxY;
extern uint8 cbreakHit;
extern int16 origCBreakSeg;
extern int16 origCBreakOfs;
extern int16 errorCodeStr;
extern uint8 fileReadBuf[];
extern uint8 byte_17D06[];
extern uint8 byte_17D16[];
extern uint8 byte_17D31[];
extern uint8 byte_17D51[];
extern uint8 byte_17D72[];
extern uint8 aFileNotFound[];
extern uint8 aNoFileBuffersAvailable[];
extern uint8 aOpenError[];
extern uint8 aFileClosingError[];
extern uint8 aReadError[];
extern uint8 aWriteError[];
extern int16 word_17E68;
extern int16 word_17E6A;
extern int16 fileReadPos;
extern int16 tmpFileHandle;
extern uint8 picDecodedRowBuf[];
extern int16 picScreenBufSize;
extern int16 picPageIndex;
extern int16 picRowOffset;
extern int16 picRow;
extern int16 picReadFromFilePtr;
extern char str_allocError[];
extern uint8 aBufferDeallocE[];
extern int dirDeltaX[];
extern int dirDeltaY[];
extern int gridLevelSize[];
extern int16 terrainSignature;
extern uint16 terrainBuf1[];
extern struct TerrainCountTable terrainTileCounts[];
extern int16 gridSignature;
extern int16 terrainDirtyFlag;
extern int16 gridValidFlag;
extern char a_3dt[];
extern char aRb[];
extern char aOpenErrorOn_3d[];
extern char aBadTileFileFor[];
extern char aTooManyTiles_[];
extern char aTooMuchTileDat[];
extern char a_3dg[];
extern char aRb_0[];
extern char aOpenErrorOn__0[];
extern char aBadGridFileFor[];
extern uint8 aRegn_xxx[];
extern uint8 aLb_xxx[];
extern uint8 aPg_xxx[];
extern uint8 aVn_xxx[];
extern uint8 aMe_xxx[];
extern uint8 aNc_xxx[];
extern uint8 aCe_xxx[];
extern uint8 aJp_xxx[];
extern uint8 aNa_xxx[];
extern uint8 aLibya_wld[];
extern uint8 aGulf_wld[];
extern uint8 aVn_wld[];
extern uint8 aMe_wld[];
extern uint8 aNc_wld[];
extern uint8 aCe_wld[];
extern uint8 aJp_wld[];
extern uint8 aNa_wld[];
extern int16 missionMidX;
extern int16 missionMidY;
extern unsigned int missionTargetX;
extern unsigned int missionTargetY;
extern int16 missionTarget2X;
extern int16 missionTarget2Y;
extern int16 missionBase2X;
extern int16 missionBase2Y;
extern uint8 aNone[];
extern uint8 aSa2[];
extern uint8 aSa5[];
extern uint8 aSa8b[];
extern uint8 aSa10[];
extern uint8 aSa11[];
extern uint8 aSa12[];
extern uint8 aSa13[];
extern uint8 aSaN4[];
extern uint8 aSaN5[];
extern uint8 aC[];
extern uint8 aSaN6[];
extern uint8 aSaN7[];
extern uint8 aHawk[];
extern uint8 aRapier[];
extern uint8 aK[];
extern uint8 aTiger[];
extern uint8 aSeacat[];
extern uint8 aIl76[];
extern struct Plane planes[];
extern uint8 aNone_0[];
extern uint8 aSa2_0[];
extern uint8 aSa5_0[];
extern uint8 aC_0[];
extern uint8 aSa8b_0[];
extern uint8 aSa10_0[];
extern uint8 unk_186C0[];
extern uint8 unk_186C6[];
extern uint8 aSa11_0[];
extern uint8 aSa12_0[];
extern uint8 aSa13_0[];
extern uint8 aSaN4_0[];
extern uint8 aSaN5_0[];
extern uint8 aSaN6_0[];
extern uint8 aSaN7_0[];
extern uint8 aHawk_0[];
extern uint8 aRapier_0[];
extern uint8 aTiger_1[];
extern uint8 aSeacat_0[];
extern uint8 aAa2[];
extern uint8 aAa8[];
extern uint8 aAa6[];
extern uint8 a2_0[];
extern uint8 aAa7[];
extern uint8 aAa9[];
extern uint8 aR[];
extern uint8 aAa10[];
extern uint8 aAim120[];
extern uint8 aAim9[];
extern uint8 aHarm[];
extern uint8 aPenguin[];
extern uint8 aHarpoon[];
extern uint8 aAgm65[];
extern uint8 aLgbomb[];
extern uint8 aRtbomb[];
extern uint8 aFfbomb[];
extern uint8 aAim7w[];
extern uint8 aAim9w[];
extern uint8 aSa14[];
extern uint8 aAa6_0[];
extern uint8 a2_1[];
extern uint8 aAa7_0[];
extern uint8 aAa9_0[];
extern uint8 aR_0[];
extern uint8 aAa10_0[];
extern uint8 aEquip_[];
extern struct UnitTypeRemap unitTypeRemapTable[];
extern int difficultySaved;
extern int16 nightMissionFlag;
extern uint8 aAim9m[];
extern uint8 aSidewinder[];
extern struct WeaponLoadout weaponLoadouts[];
extern struct MissionTableEntry missionTable[];
extern char *regnPlhPtr;
extern char *plhFiles[];
extern int16 off_19262[];
extern char *worldFiles[];
extern int16 targetCoordsX2[];
extern int16 targetCoordsY2[];
extern int16 targetCoordsX1[];
extern int16 targetCoordsY1[];
extern int16 targetCoordsX6[];
extern int16 targetCoordsY6[];
extern int16 targetCoordsX4[];
extern int16 targetCoordsY4[];
extern int16 targetCoordsX5;
extern int16 targetCoordsY5;
extern int16 targetCoordsX3[];
extern int16 targetCoordsY3[];
extern int16 targetCoordsX7[];
extern int16 targetCoordsY7[];
extern int16 targetCoordsX0[];
extern int16 targetCoordsY0[];
extern int16 targetCoordsX2Alt[];
extern int16 targetCoordsY2Alt[];
extern uint8 missionPickType[];
extern int16 *targetCoordsXPtrs[];
extern int16 *targetCoordsYPtrs[];
extern int16 targetCoordsCount[];
extern char aPowCamp[];
extern char aRb_4[];
extern char aWb_0[];
extern char aTd00[];
extern char aJz00[];
extern char aXv00[];
extern char aEs00[];
extern char aWx00[];
extern char aCc00[];
extern char aHz00[];
extern char aAt[];
extern int16 LIBC_DATA_START;
extern int16 word_19370;
extern int16 off_19372;
extern int16 word_19374;
extern int16 word_193C4;
extern uint8 aC_file_info[];
extern uint32 dword_193D3;
extern int16 word_193DF;
extern int16 word_193E1;
extern int16 word_193E5;
extern int16 word_193E7;
extern uint8 byte_193EA[];
extern int16 word_193EC;
extern int16 word_19402;
extern int16 word_19404;
extern int16 word_19406;
extern uint8 byte_19410;
extern uint8 byte_19411;
extern uint32 dword_19412;
extern int16 word_1941A;
extern int16 word_1941C;
extern int16 word_1941E;
extern int16 word_19420;
extern int16 __iob;
extern uint8 __iob2[];
extern int16 word_1954E;
extern int16 word_19550;
extern int16 word_19552;
extern int16 word_19554;
extern int16 word_19558;
extern int16 word_1955C;
extern uint8 byte_1955F;
extern int16 word_19560;
extern int16 word_19564;
extern int16 word_19566;
extern uint8 byte_1956A[];
extern uint8 unk_1956E[];
extern int16 word_19570;
extern uint32 dword_19572;
extern uint32 dword_19576;
extern uint8 aR6000StackOverflow[];
extern uint8 aR6003IntegerDivideBy0[];
extern uint8 aR6009NotEnoughSpaceForEn[];
extern uint8 aRunTimeError[];
extern uint8 aR6002FloatingPointNotLoa[];
extern uint8 aR6001NullPointerAssignme[];
extern uint8 LIBC_DATA_END[];
extern int armPosition;
extern int spriteBlitX;
extern int spriteBlitY;
extern int spriteBlitW;
extern int spriteBlitH;
extern int16 picReadBufEndPtr;
extern int16 picWorkDataPtr;
extern int16 picRowLength;
extern uint8 picProcessFlag0_1;
extern uint8 picLookupResult;
extern uint8 picTmp9BitCount;
extern uint8 picByte;
extern int16 picFileReadBufEnd;
extern int16 picNumberDictSlots;
extern int16 picFileWord;
extern uint8 picRemainingBitCount;
extern uint8 picByteUnsignedFlag;
extern int16 picSlotCounter;
extern uint8 picDictionaryIndex[];
extern uint8 unk_19775[];
extern uint8 unk_19778[];
extern uint8 byte_1977A[];
extern uint8 picWorkData[];
extern int16 picDecodeDictionary;
extern uint8 picDecodeIncrement[];
extern uint8 byte_19A3C[];
extern uint8 clipDivZeroHandler[];
extern uint8 byte_19B3C[];
extern uint8 byte_19CBC[];
extern uint8 byte_19DBC[];
extern int16 flag4Saved;
extern int16 theaterSaved;
extern uint8 far *moveDst;
extern char bufCoordStr;
extern uint8 gridRefRow;
extern uint8 gridRefCol;
extern uint8 gridRefRowDigit[];
extern uint8 CRT0_BSS_START[];
extern uint8 CRT0_BSS_END[];
extern char todayMissStrBuf[];
extern uint8 missionStrTrunc;
extern uint8 missionStrTruncEnd[];
extern int16 escortMissionFlag;
extern int far *gfxModeSetPtr;
extern FILE *fileHandle;
extern struct Game far *gameData;
extern int16 groundUnitCount;
extern uint8 byte_1B15A[];
extern uint8 gridBuf5[];
extern uint8 gridBuf4[];
extern int16 page1Ptr;
extern uint8 libc_bufout[];
extern uint8 gridBuf3[];
extern int16 *nearestTerrainResult;
extern uint8 gridBuf2[];
extern struct TerrainTile terrainTileBlock[];
extern uint8 wldReadBuf1[];
extern uint8 gridBuf1[];
extern char scenarioFoundArr[];
extern uint8 byte_1C822;
extern uint8 byte_1C823;
extern uint8 byte_1C824;
extern uint8 byte_1C825;
extern uint8 byte_1C826[];
extern struct WorldObject worldObjects[];
extern char terrainGrid[256];
extern int far *needSplash;
extern struct Target targets[];
extern int16 playerStartLoc;
extern struct FlightUnit flightUnits[];
extern uint8 hercFlag;
extern uint8 byte_1D2DD[];
extern uint8 libc_bufin[];
extern uint32 baseXPrecise;
extern int16 nearestObjectType;
extern int16 nearestDist;
extern uint32 nearestWorldX;
extern uint32 nearestWorldY;
extern struct TerrainTile* nearestTilePtr;
extern uint8 nearestLevel;
extern uint8 nearestCellIdx;
extern uint8 nearestGridX;
extern uint8 nearestGridY[];
extern uint8 exitCode[];
extern char objectTypeTable[];
extern uint32 baseYPrecise;
extern uint8 byte_1D654[];
extern uint8 byte_1DBC6[];
extern uint8 byte_1DC3C[];
extern int readItemSize;
extern uint8 wldReadBuf8[];
extern uint8 intRegs[];
extern uint8 unk_1DCD2[];
extern uint8 wldReadBuf7[];
extern int16 missionDistAccum;
extern int selectedPilotIdx;
extern int flightUnitCount;
extern uint8 joyReady[];
extern char *wldOffsets[];
extern char wldReadBuf11[];
extern struct TerrainPtrTable terrainTilePtrs[];
extern struct TerrainTile* tileDataPtr;
extern uint8 byte_1E24C[];
extern uint16 worldObjectCount;
extern struct GameComm far *commData;
extern struct Pilot hallfameBuf[];
extern uint8 libc_buferr[];
extern uint16 menuSprites;
#endif // F15_SE2_START
