#ifndef F15_SE2_STDATA
#define F15_SE2_STDATA
/* Public data globals defined in stdata.c. */
#include "inttype.h"
#include "struct.h"
#include "comm.h"
#include "pointers.h"
#include <dos.h>
#include <stdio.h>

extern char aTemp_wld[];
extern int16 *bufPtr;
extern char aDifficulty[];
extern char aTheater[];
extern char aNoScenarioFile[];
extern char aSeeTechnicalSu[];
extern char aMissionType[];
extern struct PageDesc page1Desc;
extern int16 *page1NumPtr;
extern int16 *page2NumPtr;
extern char *missTheaNames[];
extern char *missTheaDesc[];
extern char *missDiffLevels[];
extern char *missDiffDesc[];
extern char *scenarioCodePtr[];
extern char *missScenarioNames[];
extern char *missScenarioDesc[];
extern char *missTypeNames[];
extern char *missTypeDesc[];
extern char *missHistorical1Names[];
extern char *missHistorical1Desc[];
extern char *missHistorical2Names[];
extern char *missHistorical2Desc[];
extern char *missionStr;
extern int16 armSrcX[];
extern int16 armSrcY[];
extern int16 armBlitX[];
extern int16 armBlitY[];
extern int16 armBlitW[];
extern int16 armBlitH[];
extern int16 enableHighlight;
extern char *plh3d3Ptr;
extern int16 missionPick;
extern int16 armSpriteIndex[];
extern char aRepeatLastMiss[];
extern char aPleaseReinsert[];
extern char aPressSelectorW[];
extern char aDecodingMissio[];
extern char aTodaySMission[];
extern char aTakeoffFrom[];
extern char aOnc_2[];
extern char aPrimaryTarget[];
extern char aOnc_0[];
extern char aSecondaryTarge[];
extern char aOnc_1[];
extern int16 joyRepeatFlag;
extern struct SpriteParams spriteParams;
extern uint8 timerCounter;
extern uint8 timerCounter3;
extern uint8 pilotSelectFlag;
extern struct PageDesc screenDesc;
extern int16 *screenBuf;
extern int16 *pageNumPtr;
extern char *ranks[];
extern uint8 medalSpriteX[];
extern uint8 medalSpriteY[];
extern uint8 medalWidth[];
extern char aOriginalDiskIn[];
extern char aPressAKeyToCon[];
extern char aUseSelectorToC[];
extern char strOpenParen[];
extern char strCloseParen[];
extern int16 blinkColors[];
extern int16 blinkColorIdx;
extern char aMenterYourName[];
extern int16 pilotNameInputColors[];
extern uint8 joyAxes[];
extern int16 lineX1;
extern int16 lineX2;
extern int16 lineY1;
extern int16 lineY2;
extern uint8 cbreakHit;
extern char str_allocError[];
extern int dirDeltaX[];
extern int dirDeltaY[];
extern int gridLevelSize[];
extern int16 terrainSignature;
extern uint16 terrainBuf1[];
extern struct TerrainCountTable terrainTileCounts[];
extern int16 gridSignature;
extern int16 terrainDirtyFlag;
extern int16 gridValidFlag;
extern char a_3dt[];
extern char aOpenErrorOn_3d[];
extern char aBadTileFileFor[];
extern char aTooManyTiles_[];
extern char aTooMuchTileDat[];
extern char a_3dg[];
extern char aOpenErrorOn__0[];
extern char aBadGridFileFor[];
extern int16 missionMidX;
extern int16 missionMidY;
extern unsigned int missionTargetX;
extern unsigned int missionTargetY;
extern int16 missionTarget2X;
extern int16 missionTarget2Y;
extern int16 missionBase2X;
extern int16 missionBase2Y;
extern struct Plane planes[];
extern struct UnitTypeRemap unitTypeRemapTable[];
extern int difficultySaved;
extern int16 nightMissionFlag;
extern struct WeaponLoadout weaponLoadouts[];
extern struct MissionTableEntry missionTable[];
extern char *regnPlhPtr;
extern char *plhFiles[];
extern char *worldFiles[];
extern int16 targetCoordsX6[];
extern int16 targetCoordsY6[];
extern int16 targetCoordsX2Alt[];
extern int16 targetCoordsY2Alt[];
extern uint8 missionPickType[];
extern int16 *targetCoordsXPtrs[];
extern int16 *targetCoordsYPtrs[];
extern int16 targetCoordsCount[];
extern char aPowCamp[];
extern char aTd00[];
extern char aJz00[];
extern char aXv00[];
extern char aEs00[];
extern char aWx00[];
extern char aCc00[];
extern char aHz00[];
extern char aAt[];
extern int armPosition;
extern int spriteBlitX;
extern int spriteBlitY;
extern int spriteBlitW;
extern int spriteBlitH;
extern int16 flag4Saved;
extern int16 theaterSaved;
extern uint8 far *moveDst;
extern char bufCoordStr;
extern uint8 gridRefRow;
extern uint8 gridRefCol;
extern uint8 gridRefRowDigit[];
extern char todayMissStrBuf[];
extern uint8 missionStrTrunc;
extern uint8 missionStrTruncEnd[];
extern int16 escortMissionFlag;
extern int far *gfxModeSetPtr;
extern FILE *fileHandle;
extern struct Game far *gameData;
extern int16 groundUnitCount;
extern uint8 gridBuf5[];
extern uint8 gridBuf4[];
extern int16 page1Ptr;
extern uint8 gridBuf3[];
extern int16 *nearestTerrainResult;
extern uint8 gridBuf2[];
extern struct TerrainTile terrainTileBlock[];
extern uint8 wldReadBuf1[];
extern uint8 gridBuf1[];
extern char scenarioFoundArr[];
extern struct WorldObject worldObjects[];
extern char terrainGrid[256];
extern int far *needSplash;
extern struct Target targets[];
extern int16 playerStartLoc;
extern struct FlightUnit flightUnits[];
extern uint8 hercFlag;
extern uint32 baseXPrecise;
extern int16 nearestObjectType;
extern int16 nearestDist;
extern uint32 nearestWorldX;
extern uint32 nearestWorldY;
extern struct TerrainTile* nearestTilePtr;
extern uint8 nearestLevel;
extern uint8 nearestCellIdx;
extern uint8 nearestGridX;
extern uint8 nearestGridY[];
extern uint8 exitCode[];
extern char objectTypeTable[];
extern uint32 baseYPrecise;
extern int readItemSize;
extern uint8 wldReadBuf8[];
extern uint8 intRegs[];
extern uint8 wldReadBuf7[];
extern int16 missionDistAccum;
extern int selectedPilotIdx;
extern int flightUnitCount;
extern uint8 joyReady[];
extern char *wldOffsets[];
extern char wldReadBuf11[];
extern struct TerrainPtrTable terrainTilePtrs[];
extern struct TerrainTile* tileDataPtr;
extern uint16 worldObjectCount;
extern struct GameComm far *commData;
extern struct Pilot hallfameBuf[];
extern uint16 menuSprites;

#endif /* F15_SE2_STDATA */
